### ISSUE TITLE
ArgumentOutOfRangeException when creating redirect to node in 13.2.0

### ISSUE THREAD

**Issue by BrinkTP** [Infocaster/UrlTracker#193]
**ArgumentOutOfRangeException when creating redirect to node**
_Using version: 13.2.0
After upgrading to 13.2.0, when creating a redirect from an url to a content node, an ArgumentOutOfRangeException occurs

**To Reproduce**
1. Go to 'Redirects`
2. Click on '+ new redirect'
3. Set Permanent (301)
4. Add Incoming Url (e.g. http://localhost:8031/test or /test)
5. By content, pick a node ( e.g. home)
6. Click save
7. Go to http://localhost:8031/test -> ArgumentOutOfRangeException 

**Expected behavior**
Expected to be redirected to http://localhost:8031/ when navigating to http://localhost:8031/test

**Screenshots**
![image](https://github.com/user-attachments/assets/023cbd9d-4f09-4562-b672-566db1f5cef0)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 129
 - Umbraco version 13.5.2

**Stacktrace**
ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'This url cannot be converted to a string with url type 'Absolute'')

UrlTracker.Core.Models.Url.ToString(UrlType urlType, bool ensureTrailingSlash, bool excludeQuery)
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'This url cannot be converted to a string with url type 'Absolute'')
   at UrlTracker.Core.Models.Url.ToString(UrlType urlType, Boolean ensureTrailingSlash, Boolean excludeQuery)
   at UrlTracker.Web.Processing.Handling.ContentRedirectResponseInterceptHandler.GetUrl(HttpContext context, Redirect intercept, ContentPageTargetStrategy target)
   at UrlTracker.Web.Processing.Handling.RedirectResponseInterceptHandler`1.HandleAsync(RequestDelegate next, HttpContext context, Redirect intercept)
   at UrlTracker.Middleware.UrlTrackerRedirectMiddleware.InvokeAsync(HttpContext context)
   at UrlTracker.Middleware.UrlTrackerClientErrorTrackingMiddleware.InvokeAsync(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 112
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
   at Umbraco.Forms.Web.HttpModules.ProtectFormUploadRequestsMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.InterfaceMiddlewareBinder.<>c__DisplayClass2_0.<<CreateMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by D-Inventor** [comment]
Hi @BrinkTP , thank you for reaching out and reporting this bug! We're going to have a closer look to see what's going on and we'll let you know about our findings!

**Comment by D-Inventor** [comment]
Hi @BrinkTP , I've looked into this issue, but am unable to reproduce this issue so far.

Can you perhaps tell me which domains you have configured on the content item that you redirect to or any of its ancestors? Can you also tell me more about the published state of the content item or any of its ancestors? Do you have any URL aliasses configured on your content item?

For context:
The URL Tracker attempts to redirect to the content item, for which it needs to construct an absolute URL. It takes the content item that you select and asks Umbraco for an absolute URL. From what I can tell, Umbraco should then always return an absolute URL, but in your case, Umbraco returns a relative URL for some reason.

**Comment by BrinkTP** [comment]
@D-Inventor Thanks for your reply. 

I've been trying to redirect to multiple different nodes, including the home/root node. Domainname for this is set to **truepeople.shared.local.truepeople.cloud:8031** with a Dutch culture.  I don't have any URL aliases configured, and all content items and ancestors are published. Do you have any more recommendations on why the URL might be perceived as relative?

**Comment by D-Inventor** [comment]
These sound like very normal circumstances. Your configured domain looks fine to me.

It's hard to tell. You could have a look in your appsettings.json (and transforms) and see if there is an Umbraco setting that looks suspicious perhaps. I know that there exists a setting that forces all URLs to be absolute (I can't remember what it was called). Perhaps that same setting can force a URL to be relative?

I'll dive into this a bit more and see if I can discover anything

**Comment by D-Inventor** [comment]
I created a minimal site to attempt to reproduce this issue using the package script writer:
https://psw.codeshare.co.uk/

It generated the following script:

```
# Ensure we have the version specific Umbraco templates
dotnet new install Umbraco.Templates::13.5.2 --force

# Create solution/project
dotnet new sln --name "MySolution"
dotnet new umbraco --force -n "MyProject" --friendly-name "Administrator" --email "yourown@email.com" --password "[enter your own password]" --development-database-type SQLite
dotnet sln add "MyProject"

#Add starter kit
dotnet add "MyProject" package clean

#Add Packages
dotnet add "MyProject" package UrlTracker --version 13.2.0

dotnet run --project "MyProject"
#Running
```

This minimum sample still works as expected, so I'm still not sure what's going on here

**Comment by D-Inventor** [comment]
You may also want to check if you have any custom URL Providers in your solution that generate relative URLs or packages that may affect generated URLs in your solution.

I can look further into this if you can provide a minimal reproduction path using a clean solution, for example with the script that I just shared.

**Comment by BrinkTP** [comment]
@D-Inventor I'll close the issue for now, It seems that it might be a configuring issue on my end somewhere, but I can't seem to figure out where. I also can't reproduce it in my other projects. Thank you for your quick replies.
